// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAef5EfBFDRMu2zZjxMsqbnKJtPMFaYOsQ',
    appId: '1:233088006382:web:4140bc10ede1ca4b421bff',
    messagingSenderId: '233088006382',
    projectId: 'chat-app-d853b',
    authDomain: 'chat-app-d853b.firebaseapp.com',
    storageBucket: 'chat-app-d853b.appspot.com',
    measurementId: 'G-X8ZSNVF1M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMJ-awqsjW_Xa6SGIOR91ebBjcTuaeOBc',
    appId: '1:233088006382:android:b4357cb0254d8ccf421bff',
    messagingSenderId: '233088006382',
    projectId: 'chat-app-d853b',
    storageBucket: 'chat-app-d853b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGir4Yb1uL1nUagY8Ecka1YU0RVmMdwLU',
    appId: '1:233088006382:ios:34884a2ccfbf8aa9421bff',
    messagingSenderId: '233088006382',
    projectId: 'chat-app-d853b',
    storageBucket: 'chat-app-d853b.appspot.com',
    iosClientId: '233088006382-bdbuhfsr7tnhfqot33seup7uiaim52et.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
